name: Release (Github Package Registry)

on:
  push:
    branches:
      - 'main'

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '1.3.1'
      - name: Ktlint
        run: ktlint
      - name: Run tests
        run: mvn clean test
      - name: Run Maven release
        run: ./.github/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
